### ISSUE TITLE
Новый функционал

### ISSUE THREAD

**Issue by herenickname** [feed4rz/node-autodeploy-agent#1]
Нужен конфиг со списком ключей авторизации в git-репозитории и ssh-сервера
В конфиге организовать привязку git-репо к ssh-серверу + build скрипт.
```json
{
    "servers": {
        "srv1": ["yandex.ru:22", "root", "ynd+password"],
        "srv2": ["google.com:22", "root", "ggl+password"]
    },
    "repositories": {
        "repo1": ["github.com/yandex/private.git", "login", "password"],
        "repo2": ["github.com/google/private.git", "login", "password"],
    },
    "binds": [{
        "server": "srv1",
        "repository": "repo1",
        "branch": "master",
        "homepath": "/home/yandex/PrivateProject",
        "buildscripts": ["pm2 stop all", "npm update", "pm2 start all"]
    }, {
        "server": "srv2",
        "repository": "repo2",
        "branch": "master",
        "homepath": "/home/google/PrivateProject",
        "buildscripts": ["pm2 stop all", "npm update", "pm2 start all"]
    }]
}
```

Сам агент должен переодически проверять обновления в git и если таковые имеются:
1) авторизоваться по ssh на сбинженом к этому репозиторию серверу
2) перейти в директорию репозитория на сервере (_homepath_)
3) переключиться на соответствующую ветку (_branch_) выполнить git pull
4) поочередно выполнить команды из конфига (_buildscripts_)

**Comment by feed4rz** [comment]
Лучше всего не делать как хочешь ты с подключением по ssh (либо делать, но так чтобы оно поддерживалось, а не переподключалось каждый раз при новом коммите), иначе каждое подключение будет занимать уйму времени, не говоря уже оп операции git pull самой по себе.

**Comment by herenickname** [comment]
В тело цикла какого-нибудь forEach вставить setImmediate, чтобы выполнять все проверки, подключения асинхронно, в разных "потоках".

Авторизация на ssh-сервере занимает буквально пару секунд. **git pull** и **buildscripts**, возможно, придется ждать, но тебя не должно это волновать, у тебя сразу несколько серверов поддерживают соединение и выполнение команд (см. первый абзац). 

Постоянно держать соединение к серверам - это глупо. Если ты с проектом не работаешь уже месяц, зачем тебе соединение с ssh, которое будет месяц висеть?

**Comment by herenickname** [comment]
Либо держать соединение с ssh еще пять минут после последнего апдейта
